server:
  application:
    name: client-center
  session-timeout: 1800
#    tomcat:
#        max-threads: 1000
#        min-spare-threads: 30
  port: 81
#    uri-encoding: utf-8
#security:
#  basic:
#    enabled: false
spring:
  application:
    name: client-center
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: dev
  servlet:
    multipart:
      max-file-size: 10000000
      max-request-size: 10000000
  devtools:
    restart:
      enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

  cloud:
    consul:
      config:
        format: YAML
        profileSeparator: ','
      discovery:
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        service-name: client-center
        health-check-interval: 1s
        enabled: true
        prefer-ip-address: true
      host: 192.168.139.129
      port: 8500
    loadbalancer:
      enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.library.**.domain
#[弃用]配置缓存和session存储方式，默认ehcache,可选redis,[弃用]调整至 spring cache type【shiro.用户，权限，session，spring.cache通用】
#[弃用]cacheType: ehcache
lib:
  maxBorrowNum: 3
  maxBorrowDay: 7

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  circuitBreaker:
    enabled: true